settings:
  backup: false
variables:
  username: nimit

packages:
  nvim-base:
    description: "Neovim configuration with LazyVim for base"
    files:
      - source: "nvim/base/"
        target: "~/.config/nvim"
    hooks:
      pre_deploy:
        - printf "package_name={{package_name}}\ndotfiles_dir={{dotfiles_dir}}\ntarget_dir={{target_dir}}\nusername={{username}}\n" > /tmp/dotman_vars.txt
    doctor:
      executables:
        - name: nvim
          severity: error
        - name: lazygit
          severity: warning
        - name: lazydocker
          severity: warning
        - name: lazysql
          severity: warning
  nvim-home:
    description: "Neovim configuration home use"
    depends: ["nvim-base"]
    files:
      - source: "nvim/home"
        target: "~/.config/nvim"
  cliamp:
    description: "CLI Radio"
    files:
      - source: "cliamp"
        target: "~/.config/cliamp"
        absorb_ignore:
          - "cliamp.log"
          - "cliamp.sock"
          - "cliamp.sock.pid"
          - "resume.json"
    doctor:
      executables:
        - name: cliamp
          severity: error
  hypr:
    description: "Hyprland configs"
    files:
      - source: "hypr"
        target: "~/.config/hypr/"

  voxtype:
    description: "Voice to text"
    files:
      - source: "voxtype"
        target: "~/.config/voxtype/"
  openfang:
    description: "Openclaw configs"
    files:
      - source: "zsh/extras/openfang.zsh"
        target: "~/.config/zsh/openclaw.zsh"
    doctor:
      executables:
        - name: $HOME/.openfang/bin/openfang
          severity: error
  skills:
    description: "Openclaw configs"
    files:
      - source: "skills/"
        target: "~/.agents/"
  kitty:
    description: "Kitty configs"
    files:
      - source: "kitty/"
        target: "~/.config/kitty"
  zsh:
    description: "Zsh Config for the system"
    files:
      - source: "zsh/.zshrc"
        target: "~/.zshrc"
      - source: "zsh/zsh"
        target: "~/.config/zsh/"
      - source: "zsh/starship.toml"
        target: "~/.config/starship.toml"
    doctor:
      executables:
        # --- Required (hard errors) ---
        - name: zsh
          severity: error
        - name: git
          severity: error
        # --- Shell ecosystem ---
        - name: starship
          severity: warning
        - name: eza
          severity: warning
        - name: nvim
          severity: warning

        # --- Dev tooling ---
        - name: cargo
          severity: warning
        - name: pipx
          severity: warning
        - name: bun
          severity: warning
        - name: uv
          severity: warning
